# Generated by Django 2.2.6 on 2019-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_user',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
